[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# Configurações para suporte a slugs dinâmicos
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

# Regra específica para parâmetros dinâmicos em URLs
[[redirects]]
  from = "/:slug"
  to = "/.netlify/functions/next"
  status = 200

# Configuração de headers permissivos
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
